name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cirruslabs/flutter:stable
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history for SonarCloud analysis relevancy

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'


      - name: Build Project
        run: flutter build apk # Replace with your specific build command if different

      - name: Download SonarScanner
        run: |
          mkdir -p $HOME/.sonar
          curl -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610-linux-x64.zip
          unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
          rm $HOME/.sonar/sonar-scanner.zip

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Allows access to PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}     # SonarCloud authentication token
        run: $HOME/.sonar/sonar-scanner-6.2.1.4610-linux-x64/bin/sonar-scanner \
          -Dsonar.projectKey=Sixpacks123_wolkup_app \
          -Dsonar.organization=sixpacks123 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.sources=. \
          -Dsonar.verbose=true # Enables detailed logging for troubleshooting
