name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
      with: { fetch-depth: 0 }
  
    # ① create the .env file from GitHub Secrets
    - name: Create .env
      shell: bash
      env:
        API_URL: ${{ secrets.API_URL }}
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        printf "API_URL=%s\nAPI_KEY=%s\n" "$API_URL" "$API_KEY" > .env
  
    # ② set up Flutter with Dart 3.5.3 (already fixed earlier)
    - uses: subosito/flutter-action@v2
      with: { flutter-version: '3.24.3' }
  
    - name: Get dependencies
      run: flutter pub get
  
    - name: Build
      run: flutter build apk  # or `appbundle`, `ios`, etc.
  
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


